### PR TITLE
Use the message endpoint

### PR DESCRIPTION
**Pull request by cwood**
The message endpoint should work now. Not sure why its using the reply endpoint

### CODE REVIEW

**Comment by aussio** [comment]
I ran into this same thing just now. This change seems like the way to go. You should update the docstring for the method alongside this change too though, yeah?

**Comment by cwood** [comment]
yea I can just waiting for @ridersdiscount to respond :-/

**Comment by successamp** [comment]
I'll update the docstring when I package this.  Thanks!

**Comment by aussio** [comment]
wooooo! :smiley:

**Comment by cwood** [comment]
thanks

**Pull request merged**
