### PR TITLE
add: feature to read 1-1 messages from a user similar as in rooms

### PR DESCRIPTION
**Pull request by RafTim**
I needed that feature, so instead of creating an issue, I thought that it should be very easy to get done by myself...

### CODE REVIEW

**Comment by astronouth7303** [comment]
1. Make sure docstrings match existing styles
2. You need to register a matching class to handle collection work; either the `HistoryCollection` or some new class.

**Comment by RafTim** [comment]
I'll understand the first thing abozut doc-strings, even though the whole library is NOT well documented (not describing any parameter at all).
What I don't get is the second part. How and where the is the "registering of collections" done? Is it the static urls_to_objects thing, that matches an url to a Regex of a special type?

**Comment by astronouth7303** [comment]
See the existing uses, `HistoryCollection`, `UserCollection`, etc.

**Comment by successamp** [comment]
I'll go ahead and add this.  If someone wants to register a class to handle collection work I'll be happy to look in to it again.

**Pull request merged**
