### PR TITLE
added room.latest query

### PR DESCRIPTION
**Pull request by d0c-s4vage**
Pretty simple, added room.latest query so the `not-before` parameter can be used when fetching history from a room.

### CODE REVIEW

**Comment by astronouth7303** [comment]
Does this belong on the `HistoryCollection` object somehow?

**Comment by d0c-s4vage** [comment]
Hrmm hadn't looked at putting it there. I'll take a look later.

**Comment by successamp** [comment]
Looks fine to me.  I'll publish a new package with this and more updates in a bit.

**Comment by d0c-s4vage** [comment]
Awesome! Glad to contribute

**Pull request merged**
